src/Entity/Order.php
<?php

namespace App\Entity;

use App\Entity\Order\PriceDetail;
use App\Entity\Traits;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\ORM\Mapping as ORM;
use DateTime;
use Doctrine\ORM\Mapping\Entity;
use Doctrine\DBAL\Schema\Index;

use App\Entity\Payment;
use App\Application\Sonata\MediaBundle\Entity\Media;
use JsonSerializable;
use Symfony\Component\Translation\Interval;

/**
 * Order
 *
 * @Entity(repositoryClass="App\Repository\OrderRepository")
 * @ORM\Table(name="u_order_customer",indexes={@ORM\Index(name="externalId", columns={"externalId"})})
 * @ORM\HasLifecycleCallbacks()
 */
class Order implements OrderInterface, JsonSerializable
{
    use Traits\IdTrait;
    use Traits\ExternalIdEmptyTrait;
    use Traits\TimestampableTrait;
    use Traits\DirectionTrait;
    use Traits\DirectionStockTrait;
    use Traits\StatusTrait;
    use Traits\PayedTrait;
    use Traits\InsuranceTrait;
    use Traits\SenderTrait;
    use Traits\OrderPersonTrait;
    use Traits\FilesTrait;
    use Traits\RemoveTrait;
    use Traits\PromocodeTrait;
    use Traits\NotificationListTrait;
    use Traits\CustomerDeliveryTime;
    use Traits\ShippingsTrait;
    use Traits\UtmTrait;

    /**
     * @ORM\ManyToMany(targetEntity="Package", inversedBy="packages", cascade={"remove", "persist"})
     * @ORM\JoinTable(name="order_package2")
     * @ORM\JoinColumn(onDelete="CASCADE", nullable=true)
     */
    protected $packages;

    /**
     * @ORM\ManyToMany(targetEntity="OrderPackage", inversedBy="packages", cascade={"remove", "persist"})
     * @ORM\JoinColumn(onDelete="CASCADE", nullable=true)
     */
    protected $orderPackages;

    /**
     * @ORM\ManyToMany(targetEntity="Payment", cascade={"persist"})
     * @ORM\JoinTable(name="order_customer_payment",
     *      joinColumns={@ORM\JoinColumn(name="order_id", referencedColumnName="id")},
     *      inverseJoinColumns={@ORM\JoinColumn(name="payment_id", referencedColumnName="id", nullable=true)}
     * )
     */
    protected $payments;

    /**
     * @ORM\Column(type="float", nullable=true)
     */
    protected $declaredPrice;

    /**
     * Дата приему на склад
     *
     * @var \DateTime
     *
     * @ORM\Column(type="datetime", nullable=true)
     */
    protected $receptionAt;

    /**
     * Дата выдачи
     *
     * @var \DateTime
     *
     * @ORM\Column(type="datetime", nullable=true)
     */
    protected $issueAt;

    /**
     * @ORM\Column(type="float", nullable=true)
     */
    protected $minPrice;

    /**
     * @ORM\Column(type="float", nullable=true)
     */
    protected $maxPrice;

    /**
     * @ORM\Column(type="float", nullable=true)
     */
    protected $minPriceWithPromocode;

    /**
     * @ORM\Column(type="float", nullable=true)
     */
    protected $maxPriceWithPromocode;

    /**
     * @ORM\Column(type="float", nullable=true)
     */
    protected $minPriceWithoutPromocode;

    /**
     * @ORM\Column(type="float", nullable=true)
     */
    protected $maxPriceWithoutPromocode;

    /**
     * @ORM\Column(type="float", nullable=true)
     */
    protected $price;

    /**
     * @ORM\Column(type="float", nullable=true)
     */
    protected $suspendedPrice;

    /**
     * @ORM\Column(type="boolean", nullable=true)
     */
    protected $editRecevier;

    /**
     * @ORM\Column(type="boolean", nullable=true)
     */
    protected $stopSend;

    /**
     * @ORM\Column(type="boolean", nullable=true)
     */
    protected $pauseDelivery;

    /**
     * @ORM\Column(type="boolean", nullable=true)
     */
    protected $first;

    /**
     * @ORM\Column(type="boolean", nullable=true)
     */
    protected $byCargo;

    /**
     * @var \DateTime
     * @ORM\Column(type="datetime", nullable=true)
     */
    protected $suspendDate;



    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Order\PriceDetail", mappedBy="order", cascade={"persist"})
     */
    protected $priceDetails;


    public function __construct()
    {
        $this->packages = new ArrayCollection();
        $this->orderPackages = new ArrayCollection();
        $this->payments = new ArrayCollection();
        $this->files = new ArrayCollection();
        $this->notifications = new ArrayCollection();
        $this->shippings = new ArrayCollection();
        $this->priceDetails = new ArrayCollection();
    }

    CONST STATUS_NEW = 'new';
    CONST STATUS_BOOKED = 'booked'; // Требует оформления
    CONST STATUS_WAITING = 'waiting'; // Ожидается
    CONST STATUS_ACCEPTED = 'accepted'; // Принят
    CONST STATUS_REJECTED = 'rejected'; // Отказан
    CONST STATUS_PREPARING = 'preparing'; // Подготовка к отгрузке
    CONST STATUS_NOTPAID = 'not paid'; // Ожидает оплаты
    CONST STATUS_PAID = 'paid'; // Оплачено
    CONST STATUS_READY = 'ready'; // Готов к выдаче
    CONST STATUS_DELIVERED = 'delivered'; // Выдан
    CONST STATUS_SUSPENDED = 'suspended'; // Остановлен


    #const STATUS_SHIPPING = 'shipping';

    #const STATUS_CANCELED = 'canceled';

    public static function getStatusList()
    {
        return [
            'Новый' => self::STATUS_NEW,
            'Требует оформления' => self::STATUS_BOOKED,
            'Ожидается' => self::STATUS_WAITING,
            'Принят' => self::STATUS_ACCEPTED,
            'Отказан' => self::STATUS_REJECTED,
            'Подготовка к отгрузке' => self::STATUS_PREPARING,
            'Ожидает оплаты' => self::STATUS_NOTPAID,
            'Оплачено' => self::STATUS_PAID,
            'Готов к выдаче' => self::STATUS_READY,
            'Выдан' => self::STATUS_DELIVERED,
            'Остановлен' => self::STATUS_SUSPENDED,
        ];
    }

    public function getPublicStatus()
    {
        $publicStatus = 'требует оформления';
        if ($this->getStatus() == self::STATUS_NEW || $this->getStatus() == self::STATUS_BOOKED) {
            $publicStatus = 'требует оформления';
        }
        if ($this->getStatus() == self::STATUS_WAITING) {
            $publicStatus =  'ожидается';
        }
        if ($this->getStatus() == self::STATUS_ACCEPTED) {
            $publicStatus =  'принят';
        }
        if ($this->getStatus() == self::STATUS_REJECTED) {
            $publicStatus =  'отказан';
        }
        if ($this->getStatus() == self::STATUS_PREPARING) {
            $publicStatus =  'подготовка к отгрузке';
        }
        if ($this->getStatus() == self::STATUS_NOTPAID) {
            $publicStatus =  'ожидает оплаты';
        }
        if ($this->getStatus() == self::STATUS_PAID) {
            $publicStatus =  'оплачено';
        }
        if ($this->getStatus() == self::STATUS_READY) {
            $publicStatus =  'готов к выдаче';
        }
        if ($this->getStatus() == self::STATUS_DELIVERED) {
            $publicStatus =  'выдан';

            $shipping = $this->getShipping(Shipping::TYPE_DELIVER);
            if ($shipping && $shipping->isActive() && !$this->getFileByGroup('act')) {
                $publicStatus =  'выдан*';
            }
        }

        if ($this->isPauseDelivery() || $this->isStopSend() || $this->getStatus() == self::STATUS_SUSPENDED) {
            $publicStatus =  'остановлен';
        }

        //if ($this->isStopSend()) {
        //    $publicStatus =  'отказ от отправления';
        //}

        return $publicStatus;
    }

    public function getPublicStatusClass()
    {
        $publicStatusClass = '';
        if (in_array($this->getStatus(), [
            self::STATUS_NEW,
            self::STATUS_BOOKED,
            self::STATUS_NOTPAID,
            self::STATUS_PAID,
        ])) {
            $publicStatusClass =  'red';
        }

        return $publicStatusClass;
    }

    public function getGroupingPackages()
    {
        $groupPackages = [];
        $found = false;
        foreach ($this->getPackages() as $package) {
            $found = false;
            foreach ($groupPackages as &$groupPackage) {
                if (
                    $package->getSize() == $groupPackage->getSize()
                    && $package->getWeight() == $groupPackage->getWeight()
                    && $package->getPacking() == $groupPackage->getPacking()
                    && $package->getPackingPrice() == $groupPackage->getPackingPrice()
                    && $package->getPackageType() && $groupPackage->getPackageType() && $package->getPackageType()->getId() == $groupPackage->getPackageType()->getId()
                    && $package->getPackageTypeAnother() == $groupPackage->getPackageTypeAnother()
                ) {
                    $found = true;
                    $groupPackage->setCount($groupPackage->getCount() + 1);
                    break;
                }
            }

            if (!$found) {
                $groupPackages[] = $package;
            }
        }

        return $groupPackages;
    }

    public function getPackages()
    {
        foreach ($this->packages as &$package) {
            $package->setCount(1);
        }
        return $this->packages;
    }

    public function getPackagesTypes()
    {
        $result = [];
        if ($this->packages->count() > 0) {
            foreach ($this->getPackages() as $package) {
                $typeTitle = $package->getPackageType() ? $package->getPackageType()->getTitle() : $package->getPackageTypeAnother();
                $result[$typeTitle] = $typeTitle;
            }
        } else {
            foreach ($this->orderPackages as $package) {
                $typeTitle = $package->getPackageType() ? $package->getPackageType()->getTitle() : $package->getPackageTypeAnother();
                $result[$typeTitle] = $typeTitle;
            }
        }


        return array_values($result);
    }

    public function getPackagesGroupStatus()
    {
        $result = [];
        /** @var Package $package */
        foreach ($this->getPackages() as $package) {
            if (!isset($result[$package->getStatus()])) {

src/Form/Order/SaveType.php
<?php

namespace App\Form\Order;

use App\Entity\Direction;
use App\Entity\Order;
use App\Entity\Person;
use App\Entity\Receiver;
use App\Entity\Stock;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\CheckboxType;
use Symfony\Component\Form\Extension\Core\Type\IntegerType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\TextType;

class SaveType extends AbstractType
{


    public function buildForm(FormBuilderInterface $builder, array $options)
    {

        $builder
            ->add('stockFrom', EntityType::class, [
                'class' => Stock::class
            ])
            ->add('stockTo', EntityType::class, [
                'class' => Stock::class
            ])
            ->add('receiver', EntityType::class, [
                'class' => Person::class
            ])
            ->add('sender', EntityType::class, [
                'class' => Person::class
            ])
            ->add('payer', EntityType::class, [
                'class' => Person::class
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults(array(
            'csrf_protection' => false,
            'data_class' => Order::class,
            'allow_extra_fields' => true,
        ));
    }
}

src/Form/OrderType.php
<?php

namespace App\Form;

use App\Entity\Direction;
use App\Entity\Order;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\CheckboxType;
use Symfony\Component\Form\Extension\Core\Type\IntegerType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\TextType;

class OrderType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            //->add('sender', TextType::class, ['mapped' => true])
            ->add('declaredPrice', TextType::class)
            ->add('direction', EntityType::class, ['class' => Direction::class, 'mapped' => true])
            ->add('maxPrice', TextType::class)
            ->add('minPrice', TextType::class)
            ->add('declaredPrice', TextType::class)
            ->add('byCargo', IntegerType::class)
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults(array(
            'csrf_protection' => false,
            'data_class' => Order::class,
            'allow_extra_fields' => true,
        ));
    }
}

src/Controller/PdfController.php
<?php

namespace App\Controller;

use App\Entity\Base\Direction;
use App\Entity\BatchMile;
use App\Entity\Order;
use App\Entity\Organization\Organization;
use App\Entity\Wms\WmsBatch;
use App\Entity\Wms\WmsBatchMover;
use App\Entity\Wms\WmsOrder;
use App\Entity\Wms\WmsPackage;
use App\Entity\Wms\WmsPallet;
use App\Repository\Organization\OrganizationRepository;
use App\Repository\Wms\WmsBatchRepository;
use App\Repository\Wms\WmsOrderRepository;
use App\Service\Pdf\GenerateService;
use Knp\Bundle\SnappyBundle\Snappy\Response\PdfResponse;
use Vsavritsky\SettingsBundle\Service\Settings;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Route;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Component\HttpFoundation\JsonResponse;
use Symfony\Component\HttpFoundation\Request;
use Doctrine\ORM\EntityManagerInterface;


/**
 * @Route("/pdf")
 */
class PdfController extends Controller
{

    protected $generateService;

    public function __construct(
        EntityManagerInterface $em,
        GenerateService $generateService
    )
    {
        $this->em = $em;
        $this->generateService = $generateService;
    }

    /**
     * @Route("/order/{type}/{order}", name="app.pdf.order")
     */
    public function pdfOrderAction(Request $request, $type, Order $order)
    {
        $user = $this->getUser();
        $filename = $type . '-' . $order->getId() . '.pdf';

        if (!$user || !$order || $order->getUser()->getId() != $user->getId()) {
            throw $this->createNotFoundException();
        }

        $pdf = $this->generateService->generateClient($order->getId(), $type);
        if (!$pdf) {
            throw $this->createNotFoundException();
        }

        $clientGeneratePdf[] = [
            'callback' => 'generateClient',
            'arguments' => [$order->getId(), 'driver-confirm']
        ];

        return new PdfResponse($pdf, $filename);
    }


    /**
     * @Route("/batch/mile/{type}/{batchMile}", name="app.pdf.batch.mover")
     */
    public function pdfMileBatchAction(Request $request, $type, BatchMile $batchMile)
    {
        $user = $this->getUser();
        if (!$user || !$batchMile->getCarrier() || $user->getId() !== $batchMile->getCarrier()->getId()) {
            return $this->createNotFoundException();
        }
        if (!in_array($type, ['tn', 'er'])) {
            return $this->createNotFoundException();
        }

        $settings = $this->get('settings');
        $offerDate = $settings->get('offer_date');

        $filename = $type . $batchMile->getId()  . '.pdf';
        $dataTemplate = [
            'batch'  => $batchMile,
            'order' => $batchMile->getOrder(),
            'carrier' => $batchMile->getCarrier(),
            'offerDate' => $offerDate
        ];
        $pathTempalate = 'site/pdf/batch_mover/'.$type.'.html.twig';

        $html = $this->renderView($pathTempalate, $dataTemplate);

        return new PdfResponse($this->get('knp_snappy.pdf')->getOutputFromHtml($html), $filename);
    }

}

templates/wms/pdf/order/composition.html.twig
{% extends 'template/pdfpage/template.html.twig' %}

{% block content %}

    <div class="page-content" style="padding: 60px 0; text-align: justify;">

        <div class="container" style="margin: 0 auto;max-width: 100%;">
            <img src="{{ asset('/img/doc-logo.jpg') }}" alt="" class="doc-img">
            <div class="doc-header">
                <a href="#" class="doc-logo"><img src="{{ asset('/img/doc-header.jpg') }}" alt="" style="width: 306px"></a>
                <p>Доставка грузов по России<br>119034, г. Москва, Рязанский пр-кт, дом 16, с. 4, 8 800 222 33 57, www.dot-dot.ru</p>
            </div>

            <p><b>ID заказа:</b> {{ order.externalId }}</p>
            <p><b>Вес заказа:</b> {{ order.weight }} кг</p>
            <p><b>Объем заказа:</b> {{ order.totalVolume }} м3</p>
            <p><b>Доставить до:</b> {{ order.deliveryToAt|date('d.m.Y') }}</p>
            <p><b>Получатель:</b>
                {% if order.receiver.uridical %}
                    {{ order.receiver.type }} «{{ order.receiver.companyName }}», {{ order.receiver.contactName }}, {{ order.receiver.contactPhone }}.
                {% else %}
                    {{ order.receiver.contactName }}, {{ order.receiver.contactPhone }}.
                {% endif %}
            </p>
            <p><b>Направление:</b> {{ order.stockFrom.city.title }} - {{ order.stockTo.city.title }}</p>
            <p><b>Адрес отправки:</b>  {{ order.stockFrom.address }}</p>
            <p><b>Адрес доставки:</b>   {{ order.stockTo.address }}</p>
            <p><b>Грузовые места (ID, вес, габарит места)</b></p>
            <p>
                {% for package in order.packages %}
                {{ package.externalId }} - {{ package.weight }} кг, {{ package.sizeObject.width }}см х {{ package.sizeObject.height }}см х {{ package.sizeObject.depth }}см<br>
                {% endfor %}
            </p>

        </div>
    </div>
{% endblock %}

{% block stylesheets %}
    <style>
        .container{
            position: relative;
        }
        .doc-img{
            top: -58px !important;
            position: absolute;
            right: 0;
            width: 115px;
        }
        .bg{
            background-color: #fff;
            position: relative;
            top: 6px;
        }
        .black-border{
            border-bottom: 1px solid #000;
            height: 28px;
        }
        .doc-header{
            margin-bottom: 100px;
        }
        .doc-header .doc-logo{
            display: inline-block;
            vertical-align: top;
        }
        .doc-header p{
            display: inline-block;
            vertical-align: top;
            font-size: 15px;
            color: #656565;
            margin-left: 50px;
        }
        p.bottom-line{
            display: -webkit-flex;
            display: -moz-flex;
            display: -ms-flex;
            display: -o-flex;
            display: flex;
        }
        span.line{
            width: 100%;
            border-bottom: 1px solid #000;
            display: inline-block;
        }
        p.bottom-line b{
            flex: 1 0 auto;
        }
    </style>

    <link rel="stylesheet" href="{{ asset('/css/wms.min.css') }}">
    <link rel="stylesheet" href="{{ asset('/css/fix.css') }}">
{% endblock %}

templates/wms/pdf/order/er.html.twig
{% extends 'template/pdfpage/template.html.twig' %}

{% block content %}
<div class="page-content" style="padding: 60px 0; text-align: justify;">
    
    <div class="container" style="margin: 0 auto;">
		<img src="{{ asset('/img/doc-logo.jpg') }}" alt="" class="doc-img">
        <div class="doc-header">
            <a href="#" class="doc-logo"><img src="{{ asset('/img/doc-header.jpg') }}" alt="" style="width: 306px"></a>
            <p>Доставка грузов по России<br>119034, г. Москва, Рязанский пр-кт, дом 16, с. 4, {{ '800 222 33 57'|formatPhone}}, www.dot-dot.ru</p>
        </div>
        <div class="text-center" style="margin-bottom: 50px;">
            <p>
                <b>
                    Экспедиторская расписка
                </b>
            </p>
        </div>
        <div class="pull-left">
            <p><b>Дата</b>
                {% if order.receptionAt %}{{ order.receptionAt.format('d.m.Y') }}{% else %}{{ "now"|date('d.m.Y') }}{% endif %}
            </p>
        </div>
        <div class="pull-right">
            <p><b>Номер</b> {{ order.externalId }}</p>
        </div>
        <div class="clearfix"></div>

        <p><b>Клиент</b>
            {{ format_user(order.user) }}
        </p>

        <p><b>Грузоотправитель</b>
            {% if order.sender.uridical %}
                {{ order.sender.type }} «{{ order.sender.companyName }}», {{ order.sender.inn }} {{ order.sender.contactPhone }}.
            {% else %}
                {{ order.sender.contactName }}, {{ order.sender.contactPhone }}.
            {% endif %}
        </p>
        <p><b>Получатель</b>
            {% if order.receiver.uridical %}
                {{ order.receiver.type }} «{{ order.receiver.companyName }}», {{ order.receiver.inn }} {{ order.receiver.contactPhone }}.
            {% else %}
                {{ order.receiver.contactName }}, {{ order.receiver.contactPhone }}.
            {% endif %}
        </p>
        <p><b>Экспедитор</b> ООО «ТОЧКА-ТОЧКА ЛОГИСТИКА», Рязанский пр-кт, дом 16, с. 4, 9721084356, тел. {{ '8002223357'|formatPhone}}.</p>
        <br>
        <p>
            <b>Страна происхождения груза -</b><span style="width: 160px">&nbsp;</span>
            <b>Товарный код - </b><span style="width: 160px">&nbsp;</span>
            <b>Маркировка - </b><span style="width: 160px">&nbsp;</span>
        </p>
        <p><b>Количество мест, вид упаковки</b> {{ order.totalCount }} шт.</p>
        <p>
            {% set startKeyId = 0 %}
            {% set endKeyId = 0 %}
            {% for index,package in order.groupingPackages %}
                {% if package.count > 1 %}
                    {% set endKeyId = startKeyId + package.count %}
                {% else %}
                    {% set endKeyId = startKeyId %}
                {% endif %}

                {% if startKeyId == 0 %}{% set startKeyId = 1 %}{% endif %}
                {{ order.externalId }}/{% if startKeyId < endKeyId %}{{ startKeyId }}-{{ endKeyId }}{% else %}{{ startKeyId }}{% endif %}

                /{{ package.weight }} кг, {{ not package.packageType  ? package.packageTypeAnother : package.packageType }}{% if package.packing %}, {{ package.packing.title }}{% endif %}
                <br>
                {% set startKeyId = startKeyId + package.count %}
            {% endfor %}
        </p>
        <p style="width:600px">
                <span class="pull-left">
                    <b>Вес</b> {{ order.totalWeight() }} кг
                </span>
            <span class="pull-right">
                    <b>Объем</b> {{ order.totalVolume|nformat }} м3
                </span>
            <span class="clearfix"></span>
        </p>
        <p><b>Стоимость (Объявленная ценность)</b> {{ order.declaredPrice }} руб.</p>
        <p><b>Размер упаковки -</b></p>
        <p><b>Условия:</b> доставка от {{ order.stockFrom.address }} до {{ order.stockTo.address }}, предварительная стоимость: от {{ order.minPrice|number_format(0, '.') }} до {{ order.maxPrice|number_format(0, '.') }} руб., согласно оферте опубликованной на сайте www.dot-dot.ru от {{ offerDate }} г.</p>
        <p class="black-border"><span class="bg"><b>Особые отметки </b></span></p>
        <p class="black-border"></p>
        <p class="black-border"></p>
        <p class="black-border"></p>
        <br><br>
        <p>
                <span class="pull-left">
                    <b>Подпись Экспедитора</b>
                </span>
            <span class="pull-right">
                    _________________________/__________________
                </span>
            <span class="clearfix"></span>
        </p>
        <p>По доверенности № &nbsp;&nbsp;&nbsp;&nbsp;&nbsp; от&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; .&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; . &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;г. </p>
        <br><br>
        <p>
                <span class="pull-left">
                    <b>Подпись Грузоотправителя</b>
                </span>
            <span class="pull-right">
                    _________________________/__________________
                </span>
            <span class="clearfix"></span>
        </p>
        <p>По доверенности № &nbsp;&nbsp;&nbsp;&nbsp;&nbsp; от&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; .&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; . &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;г. </p>

    </div>
</div>
{% endblock %}

{% block stylesheets %}
<style>
    .container{
        position: relative;
    }
    .doc-img{
        top: -58px !important;
        position: absolute;
        right: 0;
        width: 115px;
    }
    .bg{
        background-color: #fff;
        position: relative;
        top: 6px;
    }
    .black-border{
        border-bottom: 1px solid #000;
        height: 28px;
    }
    .doc-header{
        margin-bottom: 100px;
    }
    .doc-header .doc-logo{
        display: inline-block;
        vertical-align: top;
    }
    .doc-header p{
        display: inline-block;
        vertical-align: top;
        font-size: 15px;
        color: #656565;
        margin-left: 50px;
    }
    .doc-img{
        position: absolute;
        right: 0;
        top: 0;
        width: 115px;
    }
</style>

    <link rel="stylesheet" href="{{ asset('/css/wms.min.css') }}">
    <link rel="stylesheet" href="{{ asset('/css/fix.css') }}">
{% endblock %}